deployment:
  tasks:
    - export NITRO_PRESET=node-server
    - npm ci --include=dev
    - npm run build
    - rm -rf /home/orasiatradecom/orasia/.output
    - cp -a .output /home/orasiatradecom/orasia/.output